import { Factory } from '@/entities'

const factories: Factory[] = [
  {
    name: 'Химический завод1',
    price: 1000,
    image: '/milk-factory.png',
    income: 250,
    startIncome: 250,
    onUpgradeBoostPricePercent: 2,
    onUpgradeBoostIncome: 2,
    startUpgradePrice: 1000,
    level: 1,
    levelUnlock: 1,
  },
  {
    name: 'Химический завод2',
    price: 0,
    image: '/milk-factory.png',
    income: 150,
    onUpgradeBoostPricePercent: 2,
    onUpgradeBoostIncome: 2,
    startUpgradePrice: 2000,
    level: 1,
    levelUnlock: 1,
    startIncome: 150,
  },
  {
    name: 'Химический завод3',
    price: 0,
    image: '/milk-factory.png',
    income: 50,
    startIncome: 50,
    onUpgradeBoostPricePercent: 2,
    onUpgradeBoostIncome: 2,
    startUpgradePrice: 500,
    level: 1,
    levelUnlock: 1,
  },
  {
    name: 'Химический завод4',
    price: 20000,
    image: '/milk-factory.png',
    income: 500,
    startIncome: 500,
    onUpgradeBoostPricePercent: 2,
    onUpgradeBoostIncome: 2,
    startUpgradePrice: 2000,
    level: 1,
    levelUnlock: 5,
  },
  {
    name: 'Химический завод5',
    price: 5000,
    image: '/milk-factory.png',
    income: 200,
    startIncome: 200,
    onUpgradeBoostPricePercent: 2,
    onUpgradeBoostIncome: 2,
    startUpgradePrice: 1000,
    level: 1,
    levelUnlock: 2,
  },
]
export default factories
